---
- name: "Build Image and run container with ansible playbook"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop laravel-container
    ignore_errors: yes

  - name: remove stopped container 
    command: docker rm laravel-container
    ignore_errors: yes

  - name: remove used Image
    command: docker rmi vhmds/laravel-app
    ignore_errors: yes

  - name: build docker image from dockerfile
    command: docker build -t vhmds/laravel-app .

  - name: push image to dockerhub
    command: docker push vhmds/laravel-app